### ISSUE TITLE
Cannot find Tesla BLE

### ISSUE THREAD

**Issue by vdiogo** [tesla-local-control/tesla_ble_mqtt_docker#23]
Tried "nRF Connect" on iOS and can't seem to find the BLE Mac address in the format AA:BB:CC:DD:EE:FF.
Used another app (BLE Device Info) and still cant find the BLE Mac address in the format above.
I am able to find the device beginning with S but can't find the info related with BLE Mac address
![image](https://github.com/tesla-local-control/tesla_ble_mqtt_docker/assets/24878195/93d630f8-892c-46ec-97bc-9e844725a965)

If I start the add-on with or without the BLE Mac address, the result is always the same:
```
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/app/libcolor.sh: line 4: COLOR: unbound variable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by epenet** [comment]
You should be able to put the S...C in the ble mac field

**Comment by vdiogo** [comment]
> You should be able to put the S...C in the ble mac field

I did, restarted HA and tried to start the add-on and same log:
![image](https://github.com/tesla-local-control/tesla_ble_mqtt_docker/assets/24878195/04d1a852-3d2c-4fbf-8ce4-913e411c44af)

```
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/app/libcolor.sh: line 4: COLOR: unbound variable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by raphmur** [comment]
Yep
Thanks for the feedback. Issue came from another bug. Fixed.
