### ISSUE TITLE
Move from _core run.sh code specific to Docker

### ISSUE THREAD

**Issue by baylanger** [tesla-local-control/tesla_ble_mqtt_docker#25]
Take "docker related" code from run.sh. There's no code currently per say BUT there's a comment :)

We need to create a function named ... `validateEnvVars()` ? that validates the environment variables provided by the end user via Docker env vars.

Then add the generic product's function named `productInit()` and inside that function, the code needs to call `validateEnvVars()`

Fatal errors must use fatal and exit.

In _core there's code being added to source`../libproduct.sh` (if available).

**Comment by baylanger** [comment]
Whenever possible, need to also move the following:

`export HA_BACKEND_DISABLE=${HA_BACKEND_DISABLE:=false}`

**Comment by iainbullock** [comment]
I think this is done, I will close
