### ISSUE TITLE
mkdir: can’t create directory ‹ /share/tesla_ble_mqtt ›: No such file or directory

### ISSUE THREAD

**Issue by raphmur** [tesla-local-control/tesla_ble_mqtt_docker#26]
Issue there.
When running the addon in HAOS, the /share/ directory is accessible in write mode by docker.
However, when running the standalone docker, since we are binding the /share from the host to the container, if no sufficient permissions are granted, it will fail.
@iainbullock what do you suggest for a directory to store keys, that would be always accessible by docker?

**Comment by iainbullock** [comment]
I like the idea of assigning issues, so am happy to take this one. 

If the volume is set up correctly in docker-compose.yml, then it is read-write permission by default. Note we are binding /share/tesla_ble_mqtt not /share :

    volumes:
      - tesla_ble_mqtt:/share/tesla_ble_mqtt
 
I might need to call you to understand the issue

**Comment by raphmur** [comment]
Ok I'll close. The person has posted his docker-compose (recreated from scratch) and omitted to bind 
```volumes:
  - tesla_ble_mqtt:/share/tesla_ble_mqtt```

FYI: originates from here: https://forum.hacf.fr/t/envoyer-des-commandes-a-sa-tesla-via-mqtt-ble/43348
