### ISSUE TITLE
New install confusion

### ISSUE THREAD

**Issue by jherby2k** [tesla-local-control/tesla_ble_mqtt_docker#30]
Hello, i'm trying to get the standalone version working on a Pi Zero and am having trouble. Probably noob issues - i'm still foggy on Docker stuff.

I have done the following:
1) installed a fresh copy of raspberry Pi OS
2) Installed docker per instructions on docker.com
3) Ran `sudo docker pull iainbullock/tesla_ble_mqtt`
4) Downloaded docker-compose.yml from this repo and edited it appropriately, i think (I used the SxxxxxxC name found with a scanner in the MAC field - is that kosher?)
5) This is where i'm a bit stumped. Tried running `sudo docker compose up -d` and i get

```
external volume "tesla_ble_mqtt" not found
```

Do i need to create /share/tesla_ble_mqtt on the host OS? Or is this just for the HA add-on? Am i completely missing a step?

Sorry i feel like such a dork using docker. It hurts my head for whatever reason. All your hard work is very appreciated!

**Comment by iainbullock** [comment]
The volume should be created automatically by docker. However maybe you need to run this command:

sudo docker volume create tesla_ble_mqtt

Then try 

sudo docker compose up -d

If that doesn't work please send a copy of your docker-compose.yml

If it does work let me know and I will update the instructions

Thanks

**Comment by iainbullock** [comment]
Correct you can remove it if you prefer. I prefer the volume directory name to be something meaningful rather than have docker create a random name

**Comment by raphmur** [comment]
@jherby2k for the MAC field, you should specify the MAC address.
With a bluetooth scanner app (android or iOS), you should see devices. Your tesla will have a **name** looking like this: SxxxxxxC, but what you need to put in the config is effectively the mac address, looking like AA:BB:CC:DD:EE:FF

**Comment by iainbullock** [comment]
I'll close for now as this is improved in latest release
