### ISSUE TITLE
sentry mode

### ISSUE THREAD

**Issue by foXaCe** [tesla-local-control/tesla_ble_mqtt_docker#31]
hello
very good job. thank you
everything works fine except sentry mode for me

tesla-control send command succeeded
Received MQTT message tesla_ble/xxxxxxxxxx/sentry-mode ON VIN: xxxxxxxxxxxxxxxxxxxx COMMAND: sentry-mode
Invalid MQTT topic. Topic: tesla_ble/xxxxxxxxxxxxxxxxx/sentry-mode Message: ON

**Comment by iainbullock** [comment]
OK thanks we'll have a look at fixing this in next release

**Comment by raphmur** [comment]
Fixed and targetted for next release.

**Comment by iainbullock** [comment]
This is fixed in latest version. Please re-open iyou find otherwise
