### ISSUE TITLE
Raspberry Pi Zero W unable to find car

### ISSUE THREAD

**Issue by jherby2k** [tesla-local-control/tesla_ble_mqtt_docker#34]
This is more of an FYI than anything, but i spent much of last night and this AM trying to get it all working on a Pi Zero W, and the Tesla just doesn't show up in the bluetoothctl scans. Finally in frustration i switched to a Pi 4 and boom - there it is. Working great now.

Doesn't seem to be a range thing - i ran an extension cord right out to the car and the Pi Zero still can't pick it up.

Both running latest Raspberry Pi OS, but the Pi Zero is 32-bit only which is a pretty different OS build, as i understand it.

Just thought i'd throw this in here to save people some frustration.

**Comment by iainbullock** [comment]
I haven't checked out does the original Pi have BLE or just standard Bluetooth?

**Comment by jherby2k** [comment]
OG had neither, but the Pi Zero W added Wifi/bluetooth and allegedly BLE.

**Comment by epenet** [comment]
I have Pi Zero 2W and that one works fine.

**Comment by iainbullock** [comment]
Another possible issue is if you use 2.4GHz WiFi it interferes with Bluetooth. Use 5GHz or Ethernet if you can. Again not sure about the capabilities of your RPi

**Comment by jherby2k** [comment]
no ethernet on the Pi Zero W. It has BT 4.0 which should include BLE. Anyway, all good i'm working on a Pi 4 now.

**Comment by raphmur** [comment]
Ok nice.

FYI, I have seen on another thread that the bluetooth device was not properly started. Calling `bluetoothctl scan on` after boot made the thing come online.

Can you try it?
Boot the Pi Zero
Call  `bluetoothctl scan on`  and paste the output
Try again the docker image

**Comment by jherby2k** [comment]
i had dozens of devices show up, just not my car. Of interest, bluetoothctl seems to be constantly scanning and ignores "scan off" etc. Something weird with raspbian 32-bit maybe. My Pi 4 behaved correctly out of the box.

**Comment by iainbullock** [comment]
The other devices might be standard Bluetooth not BLE

**Comment by iainbullock** [comment]
I'll close this. We might add a 'Hardware page' for this sort of info. FYI a new version was released today. Note the config environment and HA entity names are different, which may cause breaking changes. Read CHANGELOG.md. Let me know how it goes if you decide to upgrade
