### ISSUE TITLE
Loop on startup of container after trying to update to latest docker release

### ISSUE THREAD

**Issue by jurviz** [tesla-local-control/tesla_ble_mqtt_docker#35]
Following are the log messages after trying to update to the latest release:

tesla_ble_mqtt  | ------------------------------------------------------------------------------------------------------------------------------
tesla_ble_mqtt  | tesla_ble_mqtt_docker by Iain Bullock 2024 https://github.com/iainbullock/tesla_ble_mqtt_docker
tesla_ble_mqtt  | Inspiration by Raphael Murray https://github.com/raphmur
tesla_ble_mqtt  | Instructions by Shankar Kumarasamy https://shankarkumarasamy.blog/2024/01/28/tesla-developer-api-guide-ble-key-pair-auth-and-vehicle-commands-part-3
tesla_ble_mqtt  | Configuration Options are:
tesla_ble_mqtt  | TESLA_VIN1=5YJ3E7EB0KFxxxxxx
tesla_ble_mqtt  | TESLA_VIN2=
tesla_ble_mqtt  | TESLA_VIN3=
tesla_ble_mqtt  | BLE_MAC=80:6F:B0:22:DC:8D
tesla_ble_mqtt  | MQTT_IP=192.168.8.159
tesla_ble_mqtt  | MQTT_PORT=1883
tesla_ble_mqtt  | MQTT_USER=ha
tesla_ble_mqtt  | MQTT_PWD=Not Shown
tesla_ble_mqtt  | SEND_CMD_RETRY_DELAY=
tesla_ble_mqtt  | Include subroutines
tesla_ble_mqtt  | /share/tesla_ble_mqtt already exists, existing BLE keys can be reused
tesla_ble_mqtt  | Setting up auto discovery for Home Assistant
tesla_ble_mqtt  | Setting up HA auto discovery for 5YJ3E7EB0KFxxxxxx
tesla_ble_mqtt  | DEV_ID=tesla_ble_mqtt_5YJ3E7EB0KFxxxxxx
tesla_ble_mqtt  | DEV_NAME=Tesla_BLE_MQTT_5YJ3E7EB0KFxxxxxx
tesla_ble_mqtt  | TOPIC_ROOT=tesla_ble_mqtt/5YJ3E7EB0KFxxxxxx
tesla_ble_mqtt  | Listening for Home Assistant Start (in background)
tesla_ble_mqtt  | Discarding any unread MQTT messages
tesla_ble_mqtt  | Entering listening loop
tesla_ble_mqtt  | Listening to MQTT
tesla_ble_mqtt  | Listening to BLE
tesla_ble_mqtt  | Needs updating for multi-car, only supports TESLA_VIN1 at this time. Doesn't support deprecated TESLA_VIN usage
tesla_ble_mqtt  | [NEW] Device 80:6F:B0:22:DC:8D S89e7254b656017caC
tesla_ble_mqtt  | 80:6F:B0:22:DC:8D presence detected
tesla_ble_mqtt  | Listening to MQTT
tesla_ble_mqtt  | Listening to BLE
tesla_ble_mqtt  | Needs updating for multi-car, only supports TESLA_VIN1 at this time. Doesn't support deprecated TESLA_VIN usage
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc0 (-64)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc0 (-64)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc0 (-64)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffbf (-65)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc1 (-63)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc7 (-57)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc5 (-59)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc7 (-57)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc3 (-61)
tesla_ble_mqtt  | 80:6F:B0:22:DC:8D presence detected
tesla_ble_mqtt  | Listening to MQTT
tesla_ble_mqtt  | Listening to BLE
tesla_ble_mqtt  | Needs updating for multi-car, only supports TESLA_VIN1 at this time. Doesn't support deprecated TESLA_VIN usage
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc3 (-61)
tesla_ble_mqtt  | 80:6F:B0:22:DC:8D presence detected
tesla_ble_mqtt  | Listening to MQTT
tesla_ble_mqtt  | Listening to BLE
tesla_ble_mqtt  | Needs updating for multi-car, only supports TESLA_VIN1 at this time. Doesn't support deprecated TESLA_VIN usage
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc2 (-62)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc7 (-57)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc6 (-58)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc7 (-57)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc2 (-62)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc5 (-59)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc6 (-58)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffbf (-65)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc3 (-61)
tesla_ble_mqtt  | 80:6F:B0:22:DC:8D presence detected
tesla_ble_mqtt  | Listening to MQTT
tesla_ble_mqtt  | Listening to BLE
tesla_ble_mqtt  | Needs updating for multi-car, only supports TESLA_VIN1 at this time. Doesn't support deprecated TESLA_VIN usage
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc2 (-62)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc2 (-62)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc3 (-61)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffbe (-66)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc0 (-64)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc5 (-59)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc7 (-57)
tesla_ble_mqtt  | [CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc0 (-64)
tesla_ble_mqtt  | 80:6F:B0:22:DC:8D presence detected
tesla_ble_mqtt  | Listening to MQTT
tesla_ble_mqtt  | Listening to BLE

and my updated docker-compose.yaml:

volumes:
    tesla_ble_mqtt:
    external: true
services:
  tesla_ble_mqtt:
    container_name: tesla_ble_mqtt
    image: iainbullock/tesla_ble_mqtt:latest
    environment:
      - TZ='Europe/Berlin'
      - TESLA_VIN1=5YJ3E7EB0KFxxxxxx
      - BLE_MAC=80:6F:B0:22:DC:8D
      - MQTT_IP=192.168.8.159
      - MQTT_PORT=1883
      - MQTT_USER=ha
      - MQTT_PWD=xxxxxx
    stdin_open: true
    tty: true
    entrypoint: /app/run.sh
    working_dir: /share/tesla_ble_mqtt
    volumes:
      - /home/juergen/docker-volumes/teslable:/share/tesla_ble_mqtt
      - /run/dbus:/run/dbus
    network_mode: host
    privileged: true
    #restart: no
    restart: unless-stopped
networks: {}

Any hints what i might have misconfigured? BLE mac might be wrong, found with a ble scanner on my phone.
Sorry for the formatting.

**Comment by raphmur** [comment]
Your container appears to be working find:
- Correctly started: `Entering listening loop`, then the log messages loop, which is normal
- Car presence is working: `80:6F:B0:22:DC:8D presence detected`

There are a log of messages like this: `[CHG] Device 80:6F:B0:22:DC:8D RSSI: 0xffffffc3 (-61)` which are the standard output of the `bluetoothctl` command launched to detect car presence --> not relevant for you, we will remove this from logging when this is stable.

What issue do you have? You see the entities in Home Assistant? Is the car answering to commands?

**Comment by iainbullock** [comment]
@raphmur the OP appears to be using my #latest on the Dockerhub repo. @jurviz please confirm. I suspect something is stopping the container but not appearing in the logs (remember the set +e conversation)

@jurviz we are about to release a much improved version. You could try the #dev version from Dockerhub, but note the documentation is not up to date (I will try to do this tomorrow). #dev on Github is here https://github.com/tesla-local-control/tesla_ble_mqtt_docker/tree/iain-dev

**Comment by jurviz** [comment]
I will try it out tomorrow.--Gesendet mit der WEB.DE Mail AppAm 09.07.24, 22:44 schrieb Iain Bullock ***@***.***>:

   
  @raphmur the OP appears to be using my #latest on the Dockerhub repo. @jurviz please confirm. I suspect something is stopping the container but not appearing in the logs (remember the set +e conversation) 
  @jurviz we are about to release a much improved version. You could try the #dev version from Dockerhub, but note the documentation is not up to date (I will try to do this tomorrow). #dev on Github is here https://github.com/tesla-local-control/tesla_ble_mqtt_docker/tree/iain-dev

**Comment by epenet** [comment]
Same here: can't test the dev versions due to missing platforms:
https://github.com/tesla-local-control/tesla_ble_mqtt_docker/blob/2c810a75560c0bd9b8ade6946677e7a3c3dd017d/.github/workflows/builddev.yml#L42
vs

https://github.com/tesla-local-control/tesla_ble_mqtt_docker/blob/2c810a75560c0bd9b8ade6946677e7a3c3dd017d/.github/workflows/build.yml#L42

**Comment by iainbullock** [comment]
All platforms are supported on DockerHub for the full releases. Sorry for the dev only intel. You can pull the Dockerfile and build it yourself. If I get chance later I'll upload armv7 to DockerHub

The new release will be very soon. And updated instructions. Worth waiting for as the stability is much better

**Comment by iainbullock** [comment]
> No luck with the dev image.
> 
> > no matching manifest for linux/arm64/v8 in the manifest list entries
> 
> I want to use it on a Raspberry Pi Zero 2 W.
> 
> @raphmur 
> 
> So it is expected to see all these messages during normal operation? Then it is working as i see the device and entities in HA.

There are lots of messages in this version. It might be working

The new version will be a lot quieter!

**Comment by jurviz** [comment]
I will wait for the next release and instructions.

**Comment by iainbullock** [comment]
New version released today. Note the config environment and HA entity names are different, which may cause breaking changes. Read CHANGELOG.md. Let me know how it goes

**Comment by jurviz** [comment]
Just pulled latest from docker hub. On start i get fatal errors and i can't find documentation. Which branch on github is the source of the docker image?

**Comment by jurviz** [comment]
It is up and running. Will deploy it next to the car and start testing.

**Comment by iainbullock** [comment]
OK thnaks for letting me know. Let us know how you get on

**Comment by jurviz** [comment]
After solving some network problems in my garage i could start the container. I tried to deploy the key to the car but i did not get the confirmation screen in the car to add the key.
`tesla_ble_mqtt  | Received MQTT message; topic:tesla_ble/5YJ3E7EB0KFxxxxxx/config msg:deploy-key vin:5YJ3E7EB0KFxxxxxx cmd:config
tesla_ble_mqtt  | Trying to deploy the public key to vehicle...
tesla_ble_mqtt  | Attempt 1/5
tesla_ble_mqtt  | Sending key to vin 5YJ3E7EB0KFxxxxxx, attempt 1/5
tesla_ble_mqtt  | Sent add-key request to 5YJ3E7EB0KFxxxxxx. Confirm by tapping NFC card on center console.
tesla_ble_mqtt  | KEY SENT TO VEHICLE: PLEASE CHECK YOU TESLA'S SCREEN AND ACCEPT WITH YOUR CARD
tesla_ble_mqtt  | VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
tesla_ble_mqtt  | VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
tesla_ble_mqtt  | VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
tesla_ble_mqtt  | Received MQTT message; topic:tesla_ble/5YJ3E7EB0KFxxxxxx/config msg:deploy-key vin:5YJ3E7EB0KFxxxxxx cmd:config
tesla_ble_mqtt  | Trying to deploy the public key to vehicle...
tesla_ble_mqtt  | Attempt 1/5
tesla_ble_mqtt  | Sending key to vin 5YJ3E7EB0KFxxxxxx, attempt 1/5
tesla_ble_mqtt  | Sent add-key request to 5YJ3E7EB0KFxxxxxx. Confirm by tapping NFC card on center console.
tesla_ble_mqtt  | KEY SENT TO VEHICLE: PLEASE CHECK YOU TESLA'S SCREEN AND ACCEPT WITH YOUR CARD
tesla_ble_mqtt  | VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
tesla_ble_mqtt  | VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
tesla_ble_mqtt  | VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
tesla_ble_mqtt  | VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
`

**Comment by iainbullock** [comment]
I find that often the dialog box on the car screen pops up behind the main graphic of the car so you can't press the button to approve the key

Keep trying to Deploy the key. Use your phone to press the Deploy Key on HA whilst in the car may help

**Comment by epenet** [comment]
I had difficulty with this also... until I realised that it needed the card-key at the front of the console (below the screen) and not under the armrest. Once I figured this out it worked correctly for me.

Maybe it's the same issue for you?

**Comment by jurviz** [comment]
I've tried several times now. Did a reset of the car using the two buttons on the steering wheel. Switched off the Wifi connection to connect via LTE. All requests sent did not show the prompt in the car to add the key.

**Comment by iainbullock** [comment]
I'm away until tomorrow afternoon so can't do an actual deployment until then. However the _core code was tested including deployment. If you have sorted it by then I will help you then

**Comment by jurviz** [comment]
I have made a new install on the same hardware as  home assistant and mosquitto. 
Now i get these messages:

tesla_ble_mqtt   Trying to deploy the public key to vehicle...
tesla_ble_mqtt   Attempt 1/5
tesla_ble_mqtt   Sending key to vin 5YJ3E7EB0KFxxxxxx, attempt 1/5
tesla_ble_mqtt   2024/07/14 10:35:05 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
tesla_ble_mqtt   2024/07/14 10:35:05 skt: can't find the cmd for CommandCompleteEP: 03 19 FC 00
tesla_ble_mqtt   Sent add-key request to 5YJ3E7EB0KFxxxxxx. Confirm by tapping NFC card on center console.
tesla_ble_mqtt   KEY SENT TO VEHICLE: PLEASE CHECK YOU TESLA'S SCREEN AND ACCEPT WITH YOUR CARD
tesla_ble_mqtt   VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected
tesla_ble_mqtt   VIN 5YJ3E7EB0KFxxxxxx BLE MAC & LN (80:6F:B0:22:YY:YY|S89e7254bxxxxxxcaC) presence detected

nothing happens in the car.
I have also installed mqtt explorer and can see the incoming message to mosquitto.

**Comment by jurviz** [comment]
It is finally working. Key is installed in the car and the car is accepting commands. Now on to solar excess charging.

**Comment by iainbullock** [comment]
Excellent. Was there any particular technique that worked for you or was it a case of keep doing it until it worked?

**Comment by jurviz** [comment]
I think part of the problem was the unreliable networking to the Raspberry Zero 2 W. And i put the Tesla key card on the console before sending the command.
