### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by chrispazz** [tesla-local-control/tesla_ble_mqtt_docker#41]
I am running the standalone docker on a raspberry PI 3B+ and after starting the container I get this logs:

/app/run.sh: /app/env.sh: line 10: log_debug: not found
/app/run.sh: /app/env.sh: line 19: log_debug: not found
/app/run.sh: /app/mqtt.sh: line 8: log_notice: not found
/app/run.sh: /app/env.sh: line 19: log_debug: not found
/app/run.sh: /app/env.sh: line 19: log_debug: not found
/app/run.sh: /app/env.sh: line 19: log_debug: not found
/app/run.sh: /app/env.sh: line 19: log_debug: not found
/app/run.sh: /app/env.sh: line 19: log_debug: not found
/app/run.sh: /app/env.sh: line 42: log_info: not found
/app/run.sh: /app/env.sh: line 54: log_info: not found
/app/run.sh: /app/env.sh: line 62: log_debug: not found
/app/run.sh: line 21: log_debug: not found
/app/run.sh: line 26: log_debug: not found
/app/run.sh: line 47: log_info: not found
/app/run.sh: line 686: log_debug: not found
/app/run.sh: line 45: log_debug: not found
/app/run.sh: line 19: log_debug: not found
/app/run.sh: line 30: log_debug: not found
/app/run.sh: line 31: log_debug: not found
/app/run.sh: line 32: log_debug: not found
/app/run.sh: line 33: log_debug: not found
/app/run.sh: line 56: log_debug: not found

am I wrong in something?

Thank you

**Comment by iainbullock** [comment]
No it was my fault sorry. V0.1.1 had this bug. Latest version (currently v0.1.2) will fix this

**Comment by chrispazz** [comment]
Pulled newer image.
Everything correct now, thank you :)
