### ISSUE TITLE
No logs after upgrading to latest

### ISSUE THREAD

**Issue by jherby2k** [tesla-local-control/tesla_ble_mqtt_docker#49]
Hi, i just finally got around to upgrading from 1.0.0 (or whatever it was) to 0.2.0. moved all my settings over to stack.env, removed the old container and ran `sudo docker compose up -d`.

its running, but i don't think its working. I didn't regenerate keys - the old ones are still there though inside the container:

```
sudo docker exec -it tesla_ble_mqtt sh
ls /share/tesla_ble_mqtt/
<VIN>_private.pem  <VIN>_public.pem
```

I do see things getting published to MQTT.

`sudo docker logs -f tesla_ble_mqtt` prints nothing and i confirmed the .log under /var/lib/docker/containers is actually empty. Tried setting DEBUG=true but still nothing in there.

Help!

(thanks!)

**Comment by jherby2k** [comment]
Nevermind, i'm a docker idiot. Had to manually update the image as it was still trying to use the old one.

**Comment by iainbullock** [comment]
Hopefully it is now working!
