### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by Jacke87** [tesla-local-control/tesla_ble_mqtt_docker#54]
I tried to install ist but i receiverd this error

`[20:27:36] Starting... loading /app/env.sh
[20:27:36] loading libproduct.sh
Fatal; PRESENCE_DETECTION_LOOP_DELAY: is not compliant, please check this setting
Fatal; BLE_CMD_RETRY_DELAY: is not compliant, please check this setting
Fatal; PRESENCE_DETECTION_TTL: is not compliant, please check this setting
Fatal; DEBUG: is not compliant, please check this setting
Fatal; TEMPERATURE_UNIT_FAHRENHEIT: is not compliant, please check this setting`

i add only my finn Ip adress and password from mqtt. After the error i add the time delay etc

`# Mandatory; if multiple VINs separate with , or white space
#
VIN_LIST=xxxxxxxxxxxxxxxxx
# Mandatory; Hostname or IP address
#
MQTT_SERVER=xxx.xxx.xxx.xxx
# Service port # or name
#
MQTT_PORT=1883
# If no username provided, anonymous mode.
#
MQTT_USERNAME=
# If you have special characters, wrap with ' at both ends; escape ' if needed
#
MQTT_PASSWORD=xxxxxxxxxxxxxxxx
# Default 5 (seconds)
#
BLE_CMD_RETRY_DELAY=5
# Default 120 (seconds)
#
PRESENCE_DETECTION_LOOP_DELAY=120
# Default 240 (seconds)
#
PRESENCE_DETECTION_TTL=240
# Your timezone
# Ref: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#
TZ='Europe/London'
### Default false
#
DEBUG=true
#
# WARNING; If you run Home Assistant, keep this true unless you know what you're doing
#
ENABLE_HA_FEATURES=true`

**Comment by iainbullock** [comment]
Which installation method are you using? 

Assuming it involves stack.env please post your exact stack.env (obsfurcate your sensitive info). When posting use a 'code block' so it displays correctly 

If any parameters have special characters (e.g. the password field) how have you escaped them?

There is a back slash at the end of ENABLE_HA_FEATURES=true in your post above, is that really there?

**Comment by Jacke87** [comment]
I used a Raspberry Pi uses this Guide [https://github.com/tesla-local-control/tesla_ble_mqtt_docker/blob/main/INSTALL.md](url)

` Mandatory; if multiple VINs separate with , or white space

VIN_LIST=XXXXXXXXXXXXXXXXXX

 Mandatory; Hostname or IP address

MQTT_SERVER=192.168.1.152

 Service port # or name

MQTT_PORT=1883

 If no username provided, anonymous mode.

MQTT_USERNAME=

 If you have special characters, wrap with ' at both ends; escape ' if needed

MQTT_PASSWORD=XXXXXXXXXXXX

 Default 5 (seconds)

BLE_CMD_RETRY_DELAY=5

 Default 120 (seconds)

PRESENCE_DETECTION_LOOP_DELAY=120

 Default 240 (seconds)

PRESENCE_DETECTION_TTL=240

 Your timezone
 Ref: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

TZ='Europe/London'

 Default false

TEMPERATURE_UNIT_FAHRENHEIT=false

 Default false

DEBUG=false


 WARNING; If you run Home Assistant, keep this true unless you know what you're doing

ENABLE_HA_FEATURES=true
`

![Screenshot 2024-09-09 204448](https://github.com/user-attachments/assets/7d7187a7-ca75-4783-8015-05ca471422a7)

Or did i put it in wrong directories?

**Comment by Jacke87** [comment]
I get it done by mysef 
i used the wrong command to stop and start the container
After i used  `docker compose up -d` all works fine

**Comment by iainbullock** [comment]
Excellent glad you got it sorted
